# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

MAKEOPTS="-j8"
EMERGE_DEFAULT_OPTS="--quiet-build=y --jobs=2 --load-average=10"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

#RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

GENTOO_MIRRORS="https://gentoo.c3sl.ufpr.br/"

VIDEO_CARDS="iris intel i915 fbdev vesa"

# USE flags
USE_DESKTOP="kde plasma qt6 qlm kwallet semantic-desktop activities
             declarative widgets policykit udisks upower
             startup-notification screencast"

USE_X="-xv
        X cairo dri gtk gui opengl pango sdl svg vulkan wayland 
        xcb xft xml gpm appindicator"

USE_AUDIO="alsa pulseaudio pipewire sound"

USE_MEDIA="-tiff
           a52 aac avif dts encode flac gif jpeg jpegxl mad mng
           mp3 mp4 mpeg ogg png vorbis webp x264 exif"

USE_OPTICAL="cdda cdr dvd dvdr"

USE_HARDWARE="acpi bluetooth usb udev"

USE_SYSTEM="-systemd -initramfs
            debus elogind ipv6 multilib networkmanager libtirpc
            gdbm custom-cflags networkmanager dhcp"

USE_SECURITY="-cups
              acl cet crypt pam ppds seccomp ssl"

USE_I18N="iconv icu nls spell unicode"

USE_LIBS="bzip2 ncurses openmp pcre readline zlib
          libnotify wxwidgets truetype"

USE_MISC="branding"

USE="${USE_DESKTOP} ${USE_X} ${USE_AUDIO} ${USE_MEDIA} ${USE_OPTICAL}
     ${USE_HARDWARE} ${USE_SYSTEM} ${USE_SECURITY} ${USE_I18N}
     ${USE_LIBS} ${USE_MISC}"

CPU_FLAGS_X86="aes avx avx2 avx_vnni bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 ssse3 vpclmulqdq"

PORTAGE_TMPDIR="/var/tmp/portage"

L10N="en en-US pt-BR"
